// AUTO-GENERATED by scripts/apply-brand.mjs. Do not edit manually.

export type BrandingConfig = {
  brandKey: string;
  productName: string;
  desktopTitle: string;
  bundleIdentifier: string;
  publisher: string;
  exeName: string;
  localStoragePrefix: string;
  protocolScheme: string;
  assetsDir: string;
};

export const BRANDING: BrandingConfig = {
  "brandKey": "workclaw",
  "productName": "WorkClaw",
  "desktopTitle": "WorkClaw",
  "bundleIdentifier": "dev.workclaw.runtime",
  "publisher": "WorkClaw",
  "exeName": "WorkClaw",
  "localStoragePrefix": "workclaw",
  "protocolScheme": "workclaw",
  "assetsDir": "./assets"
} as const;

export default BRANDING;
