import { cpSync, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REQUIRED_MANIFEST_FIELDS = [
  "brandKey",
  "productName",
  "desktopTitle",
  "bundleIdentifier",
  "exeName",
  "localStoragePrefix",
  "assetsDir",
];

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function replaceTemplateValue(value, replacements) {
  if (typeof value === "string") {
    return Object.entries(replacements).reduce(
      (current, [token, tokenValue]) => current.replaceAll(token, tokenValue),
      value,
    );
  }

  if (Array.isArray(value)) {
    return value.map((entry) => replaceTemplateValue(entry, replacements));
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, replaceTemplateValue(entry, replacements)]),
    );
  }

  return value;
}

function parseArgs(argv) {
  const args = [...argv];
  let brandKey = "workclaw";

  for (let index = 0; index < args.length; index += 1) {
    const current = args[index];
    if (current === "--brand") {
      brandKey = args[index + 1] || "";
      index += 1;
      continue;
    }
    if (current.startsWith("--brand=")) {
      brandKey = current.slice("--brand=".length);
    }
  }

  if (!brandKey.trim()) {
    throw new Error("Expected a non-empty brand key after --brand");
  }

  return { brandKey: brandKey.trim() };
}

function validateManifest(manifest, manifestPath) {
  for (const field of REQUIRED_MANIFEST_FIELDS) {
    if (typeof manifest[field] !== "string" || !manifest[field].trim()) {
      throw new Error(`Brand manifest ${manifestPath} is missing required field "${field}"`);
    }
  }
}

function validateAssetDirectories(assetsDir, brandKey) {
  for (const relativeDir of ["logo", "installer"]) {
    const fullPath = path.join(assetsDir, relativeDir);
    if (!existsSync(fullPath)) {
      throw new Error(`Brand asset directory not found for "${brandKey}": ${fullPath}`);
    }
  }
}

function ensureFileExists(filePath, description) {
  if (!existsSync(filePath)) {
    throw new Error(`${description} not found: ${filePath}`);
  }
}

function copyDirectoryContents(sourceDir, targetDir) {
  mkdirSync(targetDir, { recursive: true });
  cpSync(sourceDir, targetDir, { recursive: true, force: true });
}

function runOrThrow(command, args, cwd) {
  const result = spawnSync(command, args, {
    cwd,
    encoding: "utf8",
    windowsHide: true,
  });

  if (result.status !== 0) {
    throw new Error(
      `Command failed: ${command} ${args.join(" ")}\n${(result.stderr || result.stdout || "").trim()}`,
    );
  }
}

function runPnpmOrThrow(args, cwd) {
  if (process.platform === "win32") {
    runOrThrow("cmd.exe", ["/d", "/s", "/c", "pnpm", ...args], cwd);
    return;
  }

  runOrThrow("pnpm", args, cwd);
}

function generateTauriIcons({ projectRoot, sourceIconPath, outputDir }) {
  const tempOutputDir = mkdtempSync(path.join(os.tmpdir(), "workclaw-brand-icons-"));

  try {
    runPnpmOrThrow(
      [
        "--dir",
        "apps/runtime",
        "tauri",
        "icon",
        sourceIconPath,
        "--output",
        tempOutputDir,
      ],
      projectRoot,
    );
    copyDirectoryContents(tempOutputDir, outputDir);
  } finally {
    rmSync(tempOutputDir, { recursive: true, force: true });
  }
}

function materializeBrandAssets({ assetsDir, projectRoot }) {
  const frontendLogoSourcePath = path.join(assetsDir, "logo", "app-logo.png");
  const frontendLogoOutputPath = path.join(
    projectRoot,
    "apps",
    "runtime",
    "src",
    "assets",
    "branding",
    "current",
    "app-logo.png",
  );
  const tauriIconsOutputDir = path.join(projectRoot, "apps", "runtime", "src-tauri", "icons");
  const installerSourceDir = path.join(assetsDir, "installer");
  const installerOutputDir = path.join(tauriIconsOutputDir, "installer");

  ensureFileExists(frontendLogoSourcePath, "Brand frontend logo");
  ensureFileExists(path.join(installerSourceDir, "nsis-header.bmp"), "Brand installer asset");

  mkdirSync(path.dirname(frontendLogoOutputPath), { recursive: true });
  cpSync(frontendLogoSourcePath, frontendLogoOutputPath, { force: true });
  generateTauriIcons({
    projectRoot,
    sourceIconPath: frontendLogoSourcePath,
    outputDir: tauriIconsOutputDir,
  });
  copyDirectoryContents(installerSourceDir, installerOutputDir);

  return {
    frontendLogoOutputPath,
    installerOutputDir,
    tauriIconsOutputDir,
  };
}

function createGeneratedBrandingModule(manifest) {
  const lines = [
    "// AUTO-GENERATED by scripts/apply-brand.mjs. Do not edit manually.",
    "",
    "export type BrandingConfig = {",
    "  brandKey: string;",
    "  productName: string;",
    "  desktopTitle: string;",
    "  bundleIdentifier: string;",
    "  publisher: string;",
    "  exeName: string;",
    "  localStoragePrefix: string;",
    "  protocolScheme: string;",
    "  assetsDir: string;",
    "};",
    "",
    "export const BRANDING: BrandingConfig = " + `${JSON.stringify(manifest, null, 2)} as const;`,
    "",
    "export default BRANDING;",
    "",
  ];

  return lines.join("\n");
}

function loadBrandContext(projectRoot, brandKey) {
  const manifestPath = path.join(projectRoot, "branding", "brands", brandKey, "manifest.json");
  if (!existsSync(manifestPath)) {
    throw new Error(`Brand manifest not found for "${brandKey}": ${manifestPath}`);
  }

  const manifest = readJson(manifestPath);
  validateManifest(manifest, manifestPath);

  const manifestDir = path.dirname(manifestPath);
  const assetsDir = path.resolve(manifestDir, manifest.assetsDir);
  if (!existsSync(assetsDir)) {
    throw new Error(`Brand assets directory not found for "${brandKey}": ${assetsDir}`);
  }

  const runtimePackageJsonPath = path.join(projectRoot, "apps", "runtime", "package.json");
  const runtimePackage = readJson(runtimePackageJsonPath);
  const templatePath = path.join(projectRoot, "apps", "runtime", "src-tauri", "tauri.conf.template.json");
  const template = readJson(templatePath);

  return {
    assetsDir,
    brandKey,
    manifest,
    manifestDir,
    projectRoot,
    runtimePackage,
    template,
  };
}

export function applyBrand({ brandKey = "workclaw", projectRoot = process.cwd() } = {}) {
  const context = loadBrandContext(projectRoot, brandKey);
  const {
    assetsDir,
    manifest,
    runtimePackage,
    template,
  } = context;

  validateAssetDirectories(assetsDir, brandKey);
  const materializedAssets = materializeBrandAssets({ assetsDir, projectRoot });

  const brandingOutputPath = path.join(projectRoot, "apps", "runtime", "src", "branding.generated.ts");
  const tauriConfigOutputPath = path.join(projectRoot, "apps", "runtime", "src-tauri", "tauri.conf.json");

  const replacements = {
    "__PRODUCT_NAME__": manifest.productName,
    "__APP_VERSION__": runtimePackage.version,
    "__BUNDLE_IDENTIFIER__": manifest.bundleIdentifier,
    "__DESKTOP_TITLE__": manifest.desktopTitle,
  };

  const generatedTauriConfig = replaceTemplateValue(template, replacements);

  writeFileSync(brandingOutputPath, createGeneratedBrandingModule(manifest), "utf8");
  writeFileSync(tauriConfigOutputPath, `${JSON.stringify(generatedTauriConfig, null, 2)}\n`, "utf8");

  return {
    assetsDir,
    brandKey: manifest.brandKey,
    brandingOutputPath,
    frontendLogoOutputPath: materializedAssets.frontendLogoOutputPath,
    tauriConfigOutputPath,
  };
}

function main() {
  const { brandKey } = parseArgs(process.argv.slice(2));
  const result = applyBrand({
    brandKey,
    projectRoot: path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."),
  });
  process.stdout.write(
    `Applied brand "${result.brandKey}" to ${path.relative(process.cwd(), result.brandingOutputPath)}, ${path.relative(process.cwd(), result.frontendLogoOutputPath)} and ${path.relative(process.cwd(), result.tauriConfigOutputPath)}\n`,
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
