import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { after } from "node:test";

import { applyBrand } from "./apply-brand.mjs";

const projectRoot = process.cwd();
const brandingOutputPath = path.join(projectRoot, "apps", "runtime", "src", "branding.generated.ts");
const frontendLogoOutputPath = path.join(
  projectRoot,
  "apps",
  "runtime",
  "src",
  "assets",
  "branding",
  "current",
  "app-logo.png",
);
const tauriConfigOutputPath = path.join(projectRoot, "apps", "runtime", "src-tauri", "tauri.conf.json");
const tauriIconOutputPath = path.join(projectRoot, "apps", "runtime", "src-tauri", "icons", "icon.ico");

after(() => {
  applyBrand({ brandKey: "workclaw", projectRoot });
});

test("apply-brand generates the default WorkClaw frontend and Tauri outputs", () => {
  const result = applyBrand({ brandKey: "workclaw", projectRoot });
  const brandingOutput = readFileSync(brandingOutputPath, "utf8");
  const tauriConfig = JSON.parse(readFileSync(tauriConfigOutputPath, "utf8"));

  assert.equal(result.brandKey, "workclaw");
  assert.ok(existsSync(brandingOutputPath), "Expected branding.generated.ts to be written");
  assert.ok(existsSync(frontendLogoOutputPath), "Expected current app logo to be written");
  assert.ok(existsSync(tauriConfigOutputPath), "Expected tauri.conf.json to be written");
  assert.ok(existsSync(tauriIconOutputPath), "Expected Tauri icon output to be written");
  assert.match(brandingOutput, /AUTO-GENERATED by scripts\/apply-brand\.mjs/);
  assert.match(brandingOutput, /"productName": "WorkClaw"/);
  assert.match(brandingOutput, /"localStoragePrefix": "workclaw"/);
  assert.equal(tauriConfig.productName, "WorkClaw");
  assert.equal(tauriConfig.identifier, "dev.workclaw.runtime");
  assert.equal(tauriConfig.version, "0.5.4");
  assert.equal(tauriConfig.app.windows[0].title, "WorkClaw");
  assert.equal(tauriConfig.bundle.windows.nsis.headerImage, "icons/installer/nsis-header.bmp");
});

test("apply-brand generates the sample XXClaw frontend and Tauri outputs", () => {
  const result = applyBrand({ brandKey: "xxclaw", projectRoot });
  const brandingOutput = readFileSync(brandingOutputPath, "utf8");
  const tauriConfig = JSON.parse(readFileSync(tauriConfigOutputPath, "utf8"));

  assert.equal(result.brandKey, "xxclaw");
  assert.ok(existsSync(brandingOutputPath), "Expected branding.generated.ts to be written");
  assert.ok(existsSync(frontendLogoOutputPath), "Expected current app logo to be written");
  assert.ok(existsSync(tauriConfigOutputPath), "Expected tauri.conf.json to be written");
  assert.ok(existsSync(tauriIconOutputPath), "Expected Tauri icon output to be written");
  assert.match(brandingOutput, /"productName": "XXClaw"/);
  assert.match(brandingOutput, /"localStoragePrefix": "xxclaw"/);
  assert.equal(tauriConfig.productName, "XXClaw");
  assert.equal(tauriConfig.identifier, "dev.xxclaw.runtime");
  assert.equal(tauriConfig.version, "0.5.4");
  assert.equal(tauriConfig.app.windows[0].title, "XXClaw");
  assert.equal(tauriConfig.bundle.windows.nsis.headerImage, "icons/installer/nsis-header.bmp");
});
